r"""
Where this application's own bundled files are, frozen or not.

**This module stays in the application and must never move into
`bookindexcore`**, which is why `HelpController` takes an `app_root` argument
rather than importing one. Its non-frozen branch resolves relative to where
*this file* sits; moved into a shared package it would resolve into
site-packages, and every bundled-resource lookup would break silently in
development while continuing to work in the frozen build.

*The LaTeX editor found this the hard way at packaging time*: its help root
was located by `__file__` arithmetic that did not survive freezing, and it
would have shipped an installer with the whole Help system silently absent.
ToA_Builder was written frozen-aware from its first commit as a result, and so
is this. **Step 10 is packaging, which is exactly when this would otherwise
bite.**

#### The root is the package, not the repository

`wordindex/` is an installable package: it goes into site-packages with no
repository around it, and a root one level up would be site-packages itself.
So the root is the package directory, `help/` and `icons/` sit inside it, and
`pyproject.toml` declares them as package data.
"""

from __future__ import annotations

import sys
from pathlib import Path

__all__ = ["HELP_SUBDIR", "ICONS_SUBDIR", "get_app_root", "get_help_root",
           "get_icon_path", "get_icons_root", "is_frozen"]

#: The one spelling of the help directory's name. `HelpController` takes it as
#: an argument and would otherwise default to a second copy of the same
#: string, which is one too many for a fact that decides whether a frozen
#: build can find its own documentation.
HELP_SUBDIR = "help"

#: Where the application mark lives. Generated by `branding/make_marks.py` in
#: `bookindexcore` and committed here, because artwork is not something an
#: installed copy should have to build.
ICONS_SUBDIR = "icons"


def is_frozen() -> bool:
    """Whether this is running out of a PyInstaller bundle."""
    return getattr(sys, "frozen", False)


def get_app_root() -> Path:
    """
    The directory bundled resources are found under.

    Frozen, that is PyInstaller's extraction root (`sys._MEIPASS`), which is
    set for a one-file build and a one-directory one alike. Otherwise it is
    the package directory this file sits in.
    """
    if is_frozen():
        # `_MEIPASS` is absent only if `frozen` was set by something that is
        # not PyInstaller; falling back to the executable's own directory is
        # right for a one-directory build and wrong for nothing that exists.
        return Path(getattr(sys, "_MEIPASS", Path(sys.executable).parent))
    return Path(__file__).resolve().parent


def get_help_root() -> Path:
    """
    Where `toc.json` and the help topics live.

    A separate function rather than `get_app_root() / "help"` at each call
    site, so :data:`HELP_SUBDIR` is the only place the name is written.
    """
    return get_app_root() / HELP_SUBDIR


def get_icons_root() -> Path:
    """Where the application mark and the About-box wordmarks live."""
    return get_app_root() / ICONS_SUBDIR


def get_icon_path(name: str) -> Path:
    """One bundled image, by filename."""
    return get_icons_root() / name
